[package]
name = "chaos-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "chaos_vfs"
path = "src/lib.rs"

[dependencies]
chaos-dispatch = { workspace = true }
chaos-proc = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }

[lints]
workspace = true
