pub mod grep_files;
pub mod list_dir;
pub mod read_file;

use mcp_host::registry::router::McpToolRouter;

use crate::ChaosServer;

pub fn router() -> McpToolRouter<ChaosServer> {
    let router = McpToolRouter::new();
    let router = read_file::mount(router);
    let router = grep_files::mount(router);
    list_dir::mount(router)
}

/// Returns tool metadata for all arsenal tools.
///
/// The kernel calls this at boot to discover arsenal's tools without
/// hand-building schemas. Each `ToolInfo` carries the name, description,
/// JSON Schema input, and annotations generated by `#[mcp_tool]`.
pub fn tool_infos() -> Vec<mcp_host::prelude::ToolInfo> {
    vec![
        read_file::tool_info(),
        grep_files::tool_info(),
        list_dir::tool_info(),
    ]
}
