mcp_host::auto_tools!(crate::ChaosServer, "src/tools");

use mcp_host::prelude::ToolError;
use mcp_host::prelude::ToolOutput;
use mcp_host::prelude::ToolResult;
use serde::de::DeserializeOwned;

/// Returns tool metadata for all arsenal tools.
///
/// The kernel calls this at boot to discover arsenal's tools without
/// hand-building schemas. Each `ToolInfo` carries the name, description,
/// JSON Schema input, and annotations generated by `#[mcp_tool]`.
pub fn tool_infos() -> Vec<mcp_host::prelude::ToolInfo> {
    router().list()
}

pub(crate) fn tool_text_result(result: Result<String, String>) -> ToolResult {
    result.map(ToolOutput::text).map_err(ToolError::Execution)
}

pub(crate) fn deserialize_tool_params<T>(arguments: &serde_json::Value) -> Result<T, String>
where
    T: DeserializeOwned,
{
    serde_json::from_value(arguments.clone()).map_err(|e| format!("invalid arguments: {e}"))
}
