pub mod connect;
pub mod error;
pub mod handler;
pub mod protocol;
pub mod runtime;
pub mod session;
pub mod transport;

#[cfg(feature = "http")]
pub use connect::HttpBuilder;
#[cfg(feature = "stdio")]
pub use connect::StdioBuilder;
#[cfg(feature = "http")]
pub use connect::http;
#[cfg(feature = "stdio")]
pub use connect::stdio;
pub use error::GuestError;
pub use handler::ClientHandler;
pub use handler::ClientHandlerFuture;
pub use handler::ClientHandlerResultFuture;
pub use handler::NoopClientHandler;
pub use protocol::*;
pub use session::McpSession;
